[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge"]
name = "clinpgx-lookup"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
clinpgx-lookup = { cmd = "python -m clinpgx_lookup.term_lookup" }
clinpgx-check-data = { cmd = "python -m clinpgx_lookup.check_data" }

[dependencies]
ipykernel = ">=6.30.1,<7"
pandas = ">=2.3.1,<3"
openai = ">=1.99.1,<2"
pydantic = ">=2.11.7,<3"
