[project]
authors = ["Shlok Natarajan <shlok.natarajan@gmail.com>"]
channels = ["conda-forge"]
name = "clinpgx-lookup"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
clinpgx-lookup = { cmd = "python -m clinpgx_lookup.term_lookup" }
clinpgx-check-data = { cmd = "python -m clinpgx_lookup.check_data" }
build-conda = { cmd = "conda build conda.recipe" }
build-conda-output = { cmd = "bash -lc 'conda build conda.recipe --output'" }
upload-conda = { cmd = "bash -lc 'anaconda upload --label main --skip-existing $(conda build conda.recipe --output)'" }

[dependencies]
pandas = ">=2.3.1,<3"
pydantic = ">=2.11.7,<3"
tqdm = ">=4.60.0"

